### ISSUE TITLE
Fails to build on Racket HEAD

### ISSUE THREAD

**Issue by samth** [jsmaniac/phc-adt#18]
See error here: https://plt.eecs.northwestern.edu/pkg-build/server/built/fail/phc-adt.txt

I haven't yet looked into what might be wrong.

**Comment by SuzanneSoy** [comment]
Thanks, I had already started investigating this. Here's a not-yet-minimal program to reproduce the issue:

```
#lang hyper-literate typed/racket/base #:no-require-lang #:no-auto-require

@chunk[<*>
       (begin
         (provide foo)
         (struct foo ())
         foo?)]
```

`hyper-literate` expands the program using `typed/racket`'s #%module-begin, and injects the resulting code in a simple module with `(#%require typed/racket)`. It does a bit of scope voodoo to try to keep the arrows in DrRacket working, and to "connect" the injected `#%require` with the expanded body. I'm trying to make a simpler test case that does not need `hyper-literate`.

This is possibly related to the new macro expander, so @mflatt might want to have a look into this once I have a minimal example.

**Comment by SuzanneSoy** [comment]
[edited above, the code I posted was incorrect]

**Comment by samth** [comment]
Can you try turning off the optimizer in TR (I don't know how to do that in hyper-literate) to see if that's related?

**Comment by SuzanneSoy** [comment]
I get the same error with this (and yes, the API for chaining languages in hyper-literate and chain-module-begin is terrible, I need to improve it):

```
#lang hyper-literate #:no-auto-require (typed/racket/base . #:no-optimize)

@chunk[<*>
       (begin
         (provide foo)
         (struct foo ())
         foo?)]
```

**Comment by SuzanneSoy** [comment]
Here's a simpler test case which reproduces the issue. Should I post this as an issue in https://github.com/racket/typed-racket/issues/ ?

`file.rkt`:
```
#lang s-exp "testlang.rkt"

(provide foo)
(struct foo ())
foo?
```

`testlang.rkt`:
```
#lang racket

(require (for-syntax racket/syntax)
         (only-in typed/racket [#%module-begin tr-module-begin]))

(define-syntax (continue stx)
  (syntax-case stx ()
    [(_continue . body)
     (let ()
       (define expanded (local-expand #`(tr-module-begin . body)
                                      'module-begin 
                                      (list)))
       (define scope (make-syntax-introducer))
       (syntax-case expanded (#%plain-module-begin)
         [(#%plain-module-begin . expanded-body)
          #`(begin . #,(scope #'expanded-body))]))]))

(define-syntax (#%module-begin stx)
  (syntax-case stx ()
    [(modbeg . body)
     #`(#%plain-module-begin
        (require #,(datum->syntax #'modbeg 'typed/racket))
        (continue . body))]))

(provide #%module-begin)
```

Error message:
```
sub1: contract violation
  expected: number?
  given: #<startup-env>
  context...:
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   perform-require!78
   for-loop
   [repeats 1 more time]
   add-lifted-require!
   do-local-lift-to-module48
   syntax-local-lift-require
   /usr/local/racket-6.90.0.29/share/pkgs/typed-racket-lib/typed-racket/utils/redirect-contract.rkt:32:2: redirect
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   loop
   lambda-clause-expander
   ...
```

**Comment by samth** [comment]
My guess is that this is a bug in the expander itself, but @mflatt may have other thoughts.

**Comment by SuzanneSoy** [comment]
Here's a shorter piece of code which triggers that error message. It is not a good test case, though, as I would not expect it to work normally (it should give an error saying that the expansion of `#%module-begin` is not a `#%plain-module-begin` form).

The error occurs after the `local-expand` finishes, even though its result is not used.

`file.rkt`:
```
#lang s-exp "testlang.rkt"

(provide foo)
(struct foo ())
foo?
```

`testlang.rkt`:
```
#lang racket

(require (for-syntax racket/syntax)
         (only-in '#%kernel [begin kernel-begin])
         (rename-in typed/racket [#%module-begin tr-module-begin]))

(define-syntax (#%module-begin stx)
  (syntax-case stx ()
    [(modbeg . body)
     (let ()
       ;; Comment out this definition, and the expected error "module: expansion
       ;; of #%module-begin is not a #%plain-module-begin form" is produced,
       ;; instead of the internal error "sub1: contract violation expected:
       ;; number? given: #<startup-env>".
       (define expanded (local-expand #`(tr-module-begin . body)
                                      'module-begin 
                                      (list)))
       #`(kernel-begin))]))

(provide #%module-begin
         (all-from-out typed/racket))
```

**Comment by mflatt** [comment]
I've pushed a repair that fixes the crashing half of the problem (which sometimes manifests as a "sub1" error). There is still a difference between the old and new expander that I haven't not sorted out, though.

**Comment by mflatt** [comment]
I've pushed a repair for the other half, and the "phc-adt" package builds for me.

**Comment by SuzanneSoy** [comment]
@mflatt A (late) thanks to you for the fix! Closing this now.
